repos:
  - repo: https://github.com/python/black
    # It must match black's version that is inside pyproject.toml
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3
        args: ["-l 80", "--exclude=.venv"]
