# Generated by Django 3.2.4 on 2021-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("PT-BR", "Português (Brasil)")],
                default="EN",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="premium",
            field=models.BooleanField(default=False),
        ),
    ]
