# Generated by Django 3.2.4 on 2021-06-26 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [
        ("polls", "0004_auto_20210625_2344"),
        ("polls", "0005_alter_poll_question"),
        ("polls", "0006_auto_20210626_1039"),
        ("polls", "0007_parentsinfo_person"),
        ("polls", "0008_alter_parentsinfo_person"),
    ]

    dependencies = [
        ("polls", "0003_alter_choice_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="author",
        ),
        migrations.RemoveField(
            model_name="question",
            name="premium",
        ),
        migrations.RemoveField(
            model_name="question",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="question",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2021, 6, 26, 10, 39, 46, 562526, tzinfo=utc
                ),
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ParentsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mothers_first_name", models.CharField(max_length=30)),
                ("mothers_last_name", models.CharField(max_length=30)),
                ("fathers_first_name", models.CharField(max_length=30)),
                ("fathers_last_name", models.CharField(max_length=30)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="polls.person",
                    ),
                ),
            ],
        ),
    ]
