# Generated by Django 3.2.4 on 2021-06-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_choice_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="author",
        ),
        migrations.RemoveField(
            model_name="question",
            name="premium",
        ),
        migrations.RemoveField(
            model_name="question",
            name="pub_date",
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(verbose_name="date published"),
                ),
                ("premium", models.BooleanField(default=False)),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll",
                        to="polls.question",
                    ),
                ),
            ],
        ),
    ]
