# Generated by Django 3.2.4 on 2021-06-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_auto_20210625_2344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll",
                to="polls.question",
            ),
        ),
    ]
