# Generated by Django 3.2.4 on 2021-06-26 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_poll_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2021, 6, 26, 10, 39, 46, 562526, tzinfo=utc
                ),
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Poll",
        ),
    ]
