# Generated by Django 3.2.4 on 2021-06-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_parentsinfo_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentsinfo",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="polls.person",
            ),
        ),
    ]
